#!/usr/bin/env python3
"""
st-merge — Synthesize multiple AI stories into one

Two modes are selected automatically based on available data:

  simple    All selected stories are passed to the synthesizer AI which
            produces a single cohesive report. No fact-check data required.
            This is the fallback when no fact-check data exists.

  quality   Uses available fact-check data to guide the synthesis. The
            base story is the highest-scoring story. The AI that authored
            the base story performs the rewrite — it already knows the
            voice, structure and topic. Other stories contribute verified
            facts to correct weak claims, not prose to be stitched in.
            The result is a single consistent voice throughout.

The mode is chosen automatically. Use --simple or --quality to override.

In quality mode the synthesizer AI is always the author of the base story.
Use --ai only to override the synthesizer in simple mode, or use --base to
change which story (and therefore which AI) anchors the quality rewrite.

Usage:
  st-merge file.json                        # auto mode, original stories only
  st-merge --stories 1 2 3 file.json        # merge a subset of stories
  st-merge --min-score 1.3 file.json        # only merge stories scoring >= 1.3
  st-merge --all file.json                  # merge all stories including derived
  st-merge --simple file.json               # force simple mode
  st-merge --quality file.json              # force quality mode (fails if no data)
  st-merge --ai anthropic file.json         # synthesizer AI for simple mode only
  st-merge --base 3 file.json               # use story 3 as base (its AI rewrites)

Output:
  Appends a new story to the .json container. The merged story records which
  source stories and AI contributed, and which mode was used.

See README_merge.md for the full design notes and roadmap.
"""

import argparse
import hashlib
import json
import os
import subprocess
import sys
from ai_handler import process_prompt, get_ai_list, get_content, get_ai_model, \
    get_default_ai
from mmd_branding import get_speaking_tagline, get_tagline_for_reading, get_app_tag, get_ai_make_model
from mmd_for_speaking import for_speaking
from mmd_process_report import remove_markdown, remove_story_break, get_hashtags, remove_hashtags, \
    clean_newlines_preserve_paragraphs, extract_title, edit_title
from mmd_util import build_segments
from mmd_startup import load_cross_env, require_config


def get_prompt(reports, orig_prompt):
    all_reports = ""
    for i, report in enumerate(reports, start=1):
        all_reports += f"Start_report: {i}\n\n"
        all_reports += report
        all_reports += f"End_report: {i}\n\n"

    prompt = f"""
You are an AI Editor. 
Your task is to create a master report that synthesizes {len(reports)} reports 
generated by different AI models, combining their insights into a cohesive and 
comprehensive document without redundancy.
Instructions
Follow these steps:
(1) Carefully review all {len(reports)} reports to understand their key points and unique insights.
(2) Identify common information across the reports and unique details omitted by some,
ensuring all valuable content is included.
(3) Synthesize the information into a single narrative, avoiding repetition and ensuring
the master report is not {len(reports)} times as long as a single report.
(4) Rewrite the introduction to reflect the synthesized content and set the context,
and rewrite the summary to encapsulate key findings.
(5) Maintain a logical flow and resolve any discrepancies by noting them or presenting
both perspectives if unresolved.

Input and Output Specifications
+ The input consists of {len(reports)} reports (provided as text or attachments) generated by different 
AI models using the same initial prompt, and optionally the original prompt for context.
+ The output is a single master report, approximately the length of one original report
(e.g., 2000 words if each report is 2000 words), formatted as a professional document
with a rewritten introduction, body, and summary.
+ Additional Considerations
Given the potential complexity of processing {len(reports)} reports,
process them simultaneously for efficiency, using your full context window.
If this proves challenging, merge incrementally: first reports 1 and 2, then add report 3,
then report 4, ensuring coherence at each step.
The original prompt for is provided context, but base the master report on the reports' content.
Ensure the report is concise, avoiding unnecessary repetition, especially in the introduction
and summary.

Here are the reports {all_reports}:

Here is the original prompt for context:
Original_prompt_start.
{orig_prompt}
Original_prompt_end.
    """
    return prompt.strip()


def get_quality_prompt(reports_with_scores, orig_prompt):
    """
    Quality-mode prompt: provides per-story average fact-check scores so the
    synthesizer can weight higher-quality sources more heavily and flag or
    avoid content from lower-scoring stories.
    """
    all_reports = ""
    for i, (report, score, make, model) in enumerate(reports_with_scores, start=1):
        score_str = f"{score:.2f}" if score is not None else "no fact-check data"
        all_reports += f"Start_report: {i}  (source: {make}/{model}, avg fact-check score: {score_str})\n\n"
        all_reports += report
        all_reports += f"End_report: {i}\n\n"

    n = len(reports_with_scores)
    prompt = f"""
You are an AI Editor with access to fact-check quality scores for each report.

Your task is to synthesize {n} reports into a single authoritative master report.
The reports were generated by different AI models on the same topic. Each report
has been assigned an average fact-check score from 0.0 (poor) to 2.0 (excellent).

Instructions:
(1) Use the fact-check scores as a quality signal. Prefer content from higher-scoring
    reports. Be cautious with content from reports scoring below 1.0.
(2) Where reports disagree on a specific fact, prefer the version from the
    higher-scoring report(s).
(3) Synthesize into a single cohesive narrative — approximately the length of one
    original report. Do not simply concatenate.
(4) Rewrite the introduction and summary to reflect the synthesized content.
(5) Maintain logical flow. Note any significant factual disagreements that remain
    unresolved after weighting by score.

Here are the {n} reports with their fact-check scores:

{all_reports}

Here is the original prompt for context:
Original_prompt_start.
{orig_prompt}
Original_prompt_end.
    """
    return prompt.strip()


# ── Phase 2 helpers ───────────────────────────────────────────────────────────

# Verdict weight for consensus scoring: higher = more trustworthy
_VERDICT_WEIGHT = {
    "True":             2,
    "Partially_true":   1,
    "Opinion":          1,
    "Partially_false": -1,
    "False":           -2,
}

_WEAK_VERDICTS = {"False", "Partially_false"}
_STRONG_VERDICTS = {"True", "Opinion", "Partially_true"}


def collect_verdicts(story_entry: dict) -> dict:
    """
    Aggregate all fact-check verdicts for a story, keyed by seg_id.

    Returns:
        {seg_id: {"consensus": str, "score": float, "checkers": [{"make", "verdict"}]}}

    Consensus is the verdict with the highest weighted vote across all checkers.
    Falls back to {} if no structured claims exist.
    """
    tally: dict[int, dict] = {}  # seg_id → {verdict: count}
    checkers: dict[int, list] = {}  # seg_id → [{make, verdict}]

    for fc in story_entry.get("fact", []):
        make = fc.get("make", "?")
        for claim in fc.get("claims", []):
            sid = claim.get("seg_id")
            verdict = claim.get("verdict", "Opinion")
            if sid is None:
                continue
            tally.setdefault(sid, {})
            checkers.setdefault(sid, [])
            tally[sid][verdict] = tally[sid].get(verdict, 0) + 1
            checkers[sid].append({"make": make, "verdict": verdict})

    result = {}
    for sid, votes in tally.items():
        # weighted consensus
        best_verdict = max(votes, key=lambda v: votes[v] * _VERDICT_WEIGHT.get(v, 0))
        total = sum(votes.values())
        score = sum(_VERDICT_WEIGHT.get(v, 0) * cnt for v, cnt in votes.items()) / total
        result[sid] = {
            "consensus": best_verdict,
            "score":     score,
            "checkers":  checkers[sid],
        }
    return result


def find_best_alternative(seg_text: str, weak_verdict: str,
                          other_stories: list, synthesizer_ai: str,
                          verbose: bool, use_cache: bool) -> str | None:
    """
    Given a weak (False/Partially_false) segment, search other stories for the
    best-supported alternative covering the same claim.

    Strategy: prompt-based — ask the AI to identify which passage in the other
    stories most directly addresses the same claim and has the strongest support.

    Returns the best alternative text, or None if nothing better is found.
    """
    if not other_stories:
        return None

    alternatives = ""
    for story_i, story_entry, verdicts in other_stories:
        make = story_entry.get("make", "?")
        model = story_entry.get("model", "?")
        avg = get_avg_score(story_entry)
        avg_str = f"{avg:.2f}" if avg is not None else "n/a"
        segs = story_entry.get("segments") or build_segments(story_entry.get("text", ""))
        alternatives += f"\nStory {story_i} ({make}/{model}, avg score {avg_str}):\n"
        for seg in segs:
            sid = seg["id"]
            v = verdicts.get(sid, {})
            consensus = v.get("consensus", "")
            verdict_tag = f"[{consensus}]" if consensus else ""
            alternatives += f"  {verdict_tag} {seg['text'][:200]}\n"

    prompt = f"""You are a fact-checking assistant.

The following claim was rated "{weak_verdict}" and needs a better version:

WEAK CLAIM:
{seg_text}

Below are passages from other AI-generated reports covering the same topic.
Each passage is tagged with its consensus fact-check verdict in [brackets].

{alternatives}

Task: Find the single passage above that most directly addresses the same claim
as the WEAK CLAIM and has the strongest fact-check verdict (True or Partially_true
preferred). Return ONLY that passage text, verbatim. If no better passage exists,
return exactly: NO_ALTERNATIVE
"""
    try:
        _, _, response, _ = process_prompt(synthesizer_ai, prompt.strip(), verbose=verbose, use_cache=use_cache)
        result = get_content(synthesizer_ai, response).strip()
        if result == "NO_ALTERNATIVE" or not result:
            return None
        return result
    except Exception:
        return None


def get_quality_prompt_v2(stories_with_indices: list, base_story_i: int,
                          orig_prompt: str, synthesizer_ai: str,
                          verbose: bool, use_cache: bool) -> tuple[str, int]:
    """
    Phase 2 quality prompt: verdict-annotated paragraph-level guidance.

    The synthesizer AI is the author of the base story. It rewrites its own
    story in its own voice, incorporating verified corrections sourced from
    other AI stories. Other stories contribute facts, not prose — the voice
    stays consistent throughout because one AI writes the entire output.

    Returns (prompt_str, weak_count).
    """
    # Build verdict maps for every story
    verdict_maps = {}
    for story_i, story_entry in stories_with_indices:
        verdict_maps[story_i] = collect_verdicts(story_entry)

    # Identify the base story
    base_entry  = next(s for si, s in stories_with_indices if si == base_story_i)
    base_make   = base_entry.get("make", "")
    base_model  = base_entry.get("model", "")
    base_segs   = base_entry.get("segments") or build_segments(base_entry.get("text", ""))
    base_verdicts = verdict_maps[base_story_i]

    # Other stories for alternative lookup
    other_stories = [
        (si, s, verdict_maps[si])
        for si, s in stories_with_indices
        if si != base_story_i
    ]

    # Build annotated segment list for the prompt
    annotated_lines = []
    weak_count  = 0
    total_segs  = len(base_segs)

    for seg in base_segs:
        sid  = seg["id"]
        text = seg["text"]
        v    = base_verdicts.get(sid, {})
        consensus = v.get("consensus", "unchecked")
        checker_summary = ""
        if v.get("checkers"):
            parts = [f"{c['make']}→{c['verdict']}" for c in v["checkers"]]
            checker_summary = "  (" + ", ".join(parts) + ")"

        if consensus in _WEAK_VERDICTS:
            weak_count += 1
            if not verbose:
                print(f"    Segment {sid}: {consensus} — finding alternative…",
                      end="", flush=True)
            alt = find_best_alternative(text, consensus, other_stories,
                                        synthesizer_ai, verbose, use_cache)
            if alt:
                if not verbose:
                    print(" found")
                annotated_lines.append(
                    f"[SEG {sid} | verdict:{consensus}{checker_summary}]\n"
                    f"YOUR ORIGINAL (needs correction): {text}\n"
                    f"VERIFIED CORRECTION (from another source): {alt}\n"
                )
            else:
                if not verbose:
                    print(" none found")
                annotated_lines.append(
                    f"[SEG {sid} | verdict:{consensus}{checker_summary}]\n"
                    f"YOUR ORIGINAL (flagged — rewrite conservatively or omit): {text}\n"
                )
        else:
            annotated_lines.append(
                f"[SEG {sid} | verdict:{consensus}{checker_summary}]\n"
                f"{text}\n"
            )

    annotated_story = "\n".join(annotated_lines)

    # Summary of other stories with scores
    other_summaries = ""
    for story_i, story_entry, _ in other_stories:
        make  = story_entry.get("make", "?")
        model = story_entry.get("model", "?")
        avg   = get_avg_score(story_entry)
        avg_str = f"{avg:.2f}" if avg is not None else "n/a"
        other_summaries += f"  Story {story_i}: {make}/{model}  avg score: {avg_str}\n"

    n = len(stories_with_indices)
    prompt = f"""You are {base_make} ({base_model}).

You previously wrote the report below on this topic. It was independently
fact-checked by {n - 1} other AI systems and received the highest average
accuracy score among {n} AI-generated reports on the same subject.

Your task is to produce an improved final version of YOUR OWN report.
Write entirely in your own voice — consistent tone, rhythm, and style
from the first word to the last. Do not adopt the phrasing or style of
the correction sources.

Each paragraph of your original report is annotated with a consensus
fact-check verdict from {n - 1} independent checkers:

  [SEG n | verdict:True]           — accurate, keep as written (light editing for flow is fine)
  [SEG n | verdict:Opinion]        — unverifiable opinion, keep but frame clearly as perspective
  [SEG n | verdict:Partially_true] — mostly correct, keep with minor clarification if needed
  [SEG n | verdict:Partially_false]— inaccurate; a VERIFIED CORRECTION is provided — use it
  [SEG n | verdict:False]          — incorrect; a VERIFIED CORRECTION is provided — use it
  [SEG n | verdict:unchecked]      — no data; use your best judgment

Instructions:
(1) Rewrite the report in your own consistent voice from start to finish.
(2) For segments marked Partially_false or False:
    — Incorporate the VERIFIED CORRECTION into your rewrite.
    — Express the corrected fact in your own words — do not copy the
      correction verbatim if it sounds like a different voice.
(3) Keep True and Opinion segments substantially intact; light editing for
    flow is fine but do not change their meaning.
(4) Produce a single cohesive narrative approximately the same length as
    your original. Do not concatenate or pad.
(5) Do not include the [SEG n | verdict:...] annotations in your output.
(6) Do not mention that corrections were made or that other AI were consulted.
    The output should read as a single, authoritative, original report.

Segments: {total_segs}   Corrections to incorporate: {weak_count}

YOUR ORIGINAL REPORT (annotated):
──────────────────────────────────────────────
{annotated_story}
──────────────────────────────────────────────

Other source stories used for corrections (scores for context):
{other_summaries}

Original prompt this report was written from:
{orig_prompt}
"""
    return prompt.strip(), weak_count


def get_avg_score(story_entry):
    """Return the average fact-check score across all fact entries for a story,
    or None if no fact-check data exists."""
    facts = story_entry.get("fact", [])
    scores = [f.get("score") for f in facts if f.get("score") is not None]
    if not scores:
        return None
    return sum(scores) / len(scores)


def select_base_story(stories_with_indices):
    """
    Return the index (1-based) of the story with the highest average fact-check
    score. Falls back to story 1 if no fact-check data exists on any story.
    """
    best_idx = stories_with_indices[0][0]
    best_score = -1.0
    for idx, story_entry in stories_with_indices:
        score = get_avg_score(story_entry)
        if score is not None and score > best_score:
            best_score = score
            best_idx = idx
    return best_idx


def main():
    require_config()
    parser = argparse.ArgumentParser(
        prog='st-merge',
        description='Merge multiple stories/reports into a master story/report')
    parser.add_argument('json_file', type=str,
                        help='Path to the JSON file', metavar='file.json')
    parser.add_argument('--ai', type=str, choices=get_ai_list(), default=get_default_ai(),
                        help=f'Synthesizer AI for simple mode. In quality mode the base '
                             f'story author is always used. Default: {get_default_ai()}')
    parser.add_argument('--cache', dest='cache', action='store_true', default=True,
                        help='Enable API cache, default: enabled')
    parser.add_argument('--no-cache', dest='cache', action='store_false',
                        help='Disable API cache')
    parser.add_argument('-a', '--all', action='store_true',
                        help='Merge all stories, default is no, use stories')
    parser.add_argument('--stories',
                        nargs='+',
                        type=int,
                        default=None,
                        help='Merge selected stories (default: all original stories, '
                             'excluding fix/merge derived stories)')
    parser.add_argument('--base', type=int, default=None,
                        help='Story number to use as structural base (default: auto, highest score)')
    parser.add_argument('--min-score', type=float, default=None,
                        metavar='SCORE',
                        help='Exclude stories with avg fact-check score below this '
                             'threshold (e.g. --min-score 1.2). Applied before auto-selection.')
    parser.add_argument('--simple', action='store_true',
                        help='Force simple merge — ignore fact-check data')
    parser.add_argument('--quality', action='store_true',
                        help='Force quality merge — fail if no fact-check data exists')
    parser.add_argument('--post-check', action='store_true', default=True,
                        help='Run st-fact on merged story and show before/after score (default: on)')
    parser.add_argument('--no-post-check', dest='post_check', action='store_false',
                        help='Skip post-merge fact-check')
    parser.add_argument('-v', '--verbose', action='store_true',
                        help='Enable verbose output')
    parser.add_argument('-q', '--quiet', action='store_true',
                        help='Enable minimal output')

    args = parser.parse_args()

    if args.simple and args.quality:
        print("Error: --simple and --quality are mutually exclusive.")
        sys.exit(1)

    file_prefix = args.json_file.rsplit('.', 1)[0]
    file_json = file_prefix + ".json"
    file_prompt = file_prefix + ".prompt"

    load_cross_env()

    container_modified = False
    try:
        if not os.path.isfile(file_json):
            print(f"Error: The file {args.json_file} does not exist.")
            sys.exit(1)
        with open(file_json, 'r') as file:
            main_container = json.load(file)
    except json.JSONDecodeError:
        print(f"Error: The file {file_json} contains invalid JSON.")
        sys.exit(1)
    except Exception as e:
        print(f"An unexpected error occurred: {e}")
        sys.exit(1)

    if args.stories is not None and len(args.stories) == 1:
        print("Only 1 story provided — merge requires 2 or more stories.")
        sys.exit(1)

    story_list = main_container["story"]
    if args.all:
        args.stories = list(range(1, len(story_list) + 1))
    elif args.stories is None:
        # Auto-select: only original stories (not derived via st-fix or st-merge)
        args.stories = [
            i for i, s in enumerate(story_list, start=1)
            if not s.get("fix_mode") and not s.get("merge_mode")
        ]
        if not args.quiet and len(args.stories) < len(story_list):
            skipped = len(story_list) - len(args.stories)
            print(f"  Auto-selected {len(args.stories)} original stories "
                  f"(skipped {skipped} derived fix/merge stories)")
        if len(args.stories) < 2:
            print("Error: fewer than 2 original stories found. "
                  "Use --stories to specify manually or --all to include all.")
            sys.exit(1)

    # ── Apply --min-score filter ──────────────────────────────────────────────
    if args.min_score is not None:
        before = args.stories[:]
        args.stories = [
            i for i in args.stories
            if (sc := get_avg_score(story_list[i - 1])) is None or sc >= args.min_score
        ]
        excluded = [i for i in before if i not in args.stories]
        if excluded and not args.quiet:
            for i in excluded:
                sc = get_avg_score(story_list[i - 1])
                sc_str = f"{sc:.2f}" if sc is not None else "n/a"
                make  = story_list[i - 1].get("make", "?")
                print(f"  Excluded story {i}: {make}  score: {sc_str}  "
                      f"(below --min-score {args.min_score})")
        if len(args.stories) < 2:
            print(f"Error: fewer than 2 stories remain after --min-score {args.min_score} filter. "
                  f"Lower the threshold or use --stories to specify manually.")
            sys.exit(1)

    # ── Collect stories to merge ──────────────────────────────────────────────
    reports = []
    reports_with_scores = []
    merge_credit = get_app_tag() + "st-merge:"
    tag_separator = ''
    stories_with_indices = []

    for story_i in args.stories:
        if 1 <= story_i <= len(story_list):
            story_entry = story_list[story_i - 1]
            stories_with_indices.append((story_i, story_entry))
            reports.append(story_entry["markdown"])
            make = story_entry["make"]
            model = story_entry.get("model", "")
            title = story_entry.get("title", "")
            avg_score = get_avg_score(story_entry)
            score_str = f"{avg_score:.2f}" if avg_score is not None else "n/a"
            if not args.quiet:
                print(f"  Story {story_i}: {make}/{model}  score: {score_str}  {title[:55]}")
            reports_with_scores.append((story_entry["markdown"], avg_score, make, model))
            merge_credit += tag_separator + get_ai_make_model(make)
            tag_separator = ','
        else:
            print(f"Invalid story number: {story_i}")
            sys.exit(1)

    # ── Auto-select merge mode ────────────────────────────────────────────────
    has_fact_data = any(s.get("fact") for _, s in stories_with_indices)
    has_claims    = any(
        claim
        for _, s in stories_with_indices
        for fc in s.get("fact", [])
        for claim in fc.get("claims", [])
    )

    if args.simple:
        mode = "simple"
    elif args.quality:
        if not has_fact_data:
            print("Error: --quality requires fact-check data. Run st-fact first.")
            sys.exit(1)
        mode = "quality"
    else:
        mode = "quality" if has_fact_data else "simple"

    if not args.quiet:
        if mode == "quality":
            detail = "claims" if has_claims else "scores only"
            reason = f"(fact-check data found — {detail})"
        elif not has_fact_data:
            reason = "(no fact-check data — run st-fact or st-cross first for better results)"
        else:
            reason = "(forced)"
        print(f"\n  Mode: {mode} {reason}")

    # ── Auto-select base story ────────────────────────────────────────────────
    if args.base is not None:
        base_story_i = args.base
        if not (1 <= base_story_i <= len(story_list)):
            print(f"Error: --base {base_story_i} is out of range.")
            sys.exit(1)
    else:
        base_story_i = select_base_story(stories_with_indices)

    if not args.quiet and mode == "quality":
        base_entry = next(s for si, s in stories_with_indices if si == base_story_i)
        base_score = get_avg_score(base_entry)
        base_score_str = f"{base_score:.2f}" if base_score else "n/a"
        print(f"  Base story: {base_story_i}  ({base_entry.get('make')}/{base_entry.get('model')}  avg score: {base_score_str})")

    # ── In quality mode, lock synthesizer to the base story's author ──────────
    # The AI that wrote the best story already knows the voice, structure and
    # topic. Asking it to rewrite its own story with verified corrections
    # produces a single consistent voice throughout. Other stories contribute
    # facts, not prose.
    if mode == "quality":
        base_entry = next(s for si, s in stories_with_indices if si == base_story_i)
        base_make  = base_entry.get("make")
        if base_make and base_make in get_ai_list():
            if args.ai != base_make and not args.quiet:
                print(f"  Synthesizer: {base_make} (base story author — overrides --ai in quality mode)")
            args.ai = base_make
        else:
            if not args.quiet:
                print(f"  Synthesizer: {args.ai} (base story make '{base_make}' not in AI list — using default)")

    # ── Load original prompt for context ─────────────────────────────────────
    context_prompt = ""
    try:
        if not os.path.isfile(file_prompt):
            if not args.quiet:
                print(f"  Note: {file_prompt} not found — proceeding without original prompt context")
        else:
            with open(file_prompt, 'r') as infile:
                context_prompt = infile.read()
    except Exception as e:
        print(f"An error occurred reading prompt file: {e}", file=sys.stderr)
        sys.exit(1)

    # ── Build prompt and call AI ──────────────────────────────────────────────
    weak_count = 0
    if mode == "quality":
        if has_claims:
            # Phase 2: verdict-annotated, segment-level guidance
            if not args.quiet:
                print(f"\n  Building verdict-annotated prompt (Phase 2)…")
            prompt, weak_count = get_quality_prompt_v2(
                stories_with_indices, base_story_i,
                context_prompt, args.ai, args.verbose, args.cache
            )
            if not args.quiet:
                print(f"  Weak segments replaced/flagged: {weak_count}")
            merge_credit += ":quality-v2"
        else:
            # Phase 1 fallback: score-weighted only, no segment-level data
            prompt = get_quality_prompt(reports_with_scores, context_prompt)
            merge_credit += ":quality-v1"
    else:
        prompt = get_prompt(reports, context_prompt)
        merge_credit += ":simple"

    if not args.quiet:
        print(f"\n  Calling {args.ai} to synthesize {len(reports)} stories…", end='', flush=True)

    gen_payload, client, response, ai_model = (
        process_prompt(args.ai, prompt, verbose=args.verbose, use_cache=args.cache))

    if not args.quiet:
        print(f" ✓")
        print(f"  Processing results…")

    # ── Build data entry ──────────────────────────────────────────────────────
    data = {
        "make": args.ai,
        "model": get_ai_model(args.ai),
        "prompt": prompt,
        "gen_payload": gen_payload,
        "gen_response": response,
    }
    data_str = json.dumps(data, sort_keys=True)
    md5_hash = hashlib.md5(data_str.encode('utf-8')).hexdigest()
    data["md5_hash"] = md5_hash

    duplicate_index = None
    for index, existing_data in enumerate(main_container["data"], start=1):
        existing_hash = existing_data.get("md5_hash")
        if existing_hash == md5_hash:
            duplicate_index = index
            if args.verbose:
                print("  Data item already exists, did not add duplicate")
            break
    if duplicate_index is None:
        main_container["data"].append(data)
        container_modified = True
        if args.verbose:
            print("  Added new data item")
    else:
        if not args.quiet:
            print("  Duplicate data item — not added")

    # ── Build story entry ─────────────────────────────────────────────────────
    all_raw_story_text = get_content(args.ai, response)
    make = args.ai
    model = get_ai_model(make)

    file_md_content = remove_story_break(all_raw_story_text)
    select_hashtags = get_hashtags(file_md_content)
    hashless_story = remove_hashtags(file_md_content)
    no_md = remove_markdown(hashless_story)
    speaking_tagline = get_speaking_tagline(make, model)
    as_spoken = for_speaking(no_md, args.verbose) + "\n\n" + speaking_tagline

    ai_tag_reading = merge_credit + "\n  " + get_tagline_for_reading(make, model) + "\n  "
    clean_paragraphs = clean_newlines_preserve_paragraphs(no_md)
    file_txt_content = clean_paragraphs + "\n\n" + ai_tag_reading
    file_md_content += "\n\n" + ai_tag_reading

    file_title_content = extract_title(file_txt_content)
    file_title_content = edit_title(file_title_content)

    story = {
        "make": make,
        "model": model,
        "title": file_title_content,
        "markdown": file_md_content,
        "text": file_txt_content,
        "spoken": as_spoken,
        "hashtags": select_hashtags,
        "merge_mode": mode,
        "merge_sources": args.stories,
        "fact": [],
    }
    story_str = json.dumps(story, sort_keys=True)
    md5_hash = hashlib.md5(story_str.encode('utf-8')).hexdigest()
    story["md5_hash"] = md5_hash

    if "story" not in main_container:
        main_container["story"] = []

    duplicate_index = None
    for index, existing_story in enumerate(main_container["story"], start=1):
        existing_hash = existing_story.get("md5_hash")
        if existing_hash == md5_hash:
            duplicate_index = index
            break
    if duplicate_index is None:
        main_container["story"].append(story)
        container_modified = True
        story_num = len(main_container["story"])
        if not args.quiet:
            print(f"  Added merged story as story {story_num}  (mode: {mode})")
    else:
        if not args.quiet:
            print("  Merged story already exists — not adding duplicate")

    if container_modified:
        with open(file_json, 'w', encoding='utf-8') as f:
            json.dump(main_container, f, ensure_ascii=False, indent=4)
            f.flush()
            os.fsync(f.fileno())
        if not args.quiet:
            print(f"  Container updated: {file_json}")

    # ── Optional post-merge fact-check ────────────────────────────────────────
    if container_modified and args.post_check and mode == "quality":
        story_num = len(main_container["story"])

        # Track best individual source score for regression warning
        source_scores = [get_avg_score(s) for _, s in stories_with_indices
                         if get_avg_score(s) is not None]
        before_avg  = sum(source_scores) / len(source_scores) if source_scores else None
        before_best = max(source_scores) if source_scores else None

        # Run st-fact --ai all with full output so the user sees the live
        # progress table during the 5-10 minute fact-check.
        # --silent is intentionally NOT used — that's the whole point.
        if not args.quiet:
            print(f"\n  Post-merge fact-check — story {story_num} (all AI, unbiased):")
            print()
        try:
            subprocess.run(
                ["st-fact", "--ai", "all", "-s", str(story_num),
                 "--timeout", "20", file_json],
                check=False,
            )

            # Re-read to get the after score (avg across all new fact entries)
            with open(file_json, 'r') as f:
                updated = json.load(f)
            merged_story = updated["story"][story_num - 1]
            after_score = get_avg_score(merged_story)

            # Show per-checker breakdown
            if not args.quiet:
                print()
                print("  ── POST-MERGE FACT-CHECK ─────────────────────────────────")
                if before_avg is not None:
                    delta = (after_score - before_avg) if after_score is not None else None
                    delta_str = f"{delta:+.2f}" if delta is not None else "n/a"
                    print(f"  Source stories avg score  : {before_avg:.2f}")
                for fc in merged_story.get("fact", []):
                    fc_score = fc.get("score")
                    fc_make  = fc.get("make", "?")
                    fc_model = fc.get("model", "?")
                    score_str = f"{fc_score:.2f}" if fc_score is not None else " n/a"
                    print(f"  {fc_make:<12} {fc_model:<28} {score_str}")
                if after_score is not None:
                    print(f"  {'─'*46}")
                    print(f"  Merged story avg score    : {after_score:.2f}")
                    if before_avg is not None:
                        print(f"  Delta vs source avg       : {delta_str}")

                    # Regression warning — merged worse than best source
                    if before_best is not None and after_score < before_best:
                        best_story_i = next(
                            (si for si, s in stories_with_indices
                             if get_avg_score(s) == before_best), None)
                        best_make = story_list[best_story_i - 1].get("make", "?") \
                            if best_story_i else "?"
                        gap = before_best - after_score
                        print()
                        print(f"  ⚠  Merged score {after_score:.2f} is below best source "
                              f"story {best_story_i} ({best_make}, {before_best:.2f}) "
                              f"by {gap:.2f}")
                        print(f"  Suggestions:")
                        print(f"    • Merge only high-scoring stories:")
                        high = [si for si, s in stories_with_indices
                                if (sc := get_avg_score(s)) is not None
                                and sc >= before_best - 0.15]
                        if len(high) >= 2:
                            print(f"        st-merge --stories {' '.join(str(x) for x in high)} "
                                  f"{os.path.basename(file_json)}")
                        print(f"    • Set a score floor:")
                        print(f"        st-merge --min-score {before_best - 0.1:.1f} "
                              f"{os.path.basename(file_json)}")
                        print(f"    • Or just use story {best_story_i} as-is — it already "
                              f"outscores the merge")

                print("  ─────────────────────────────────────────────────────────")
        except FileNotFoundError:
            if not args.quiet:
                print("  Note: st-fact not found — skipping post-merge fact-check")
        except Exception as e:
            if not args.quiet:
                print(f"  Post-merge fact-check error: {e}")


if __name__ == "__main__":
    main()
